---
title: ModelValidationError (v0.19)
description: API reference for qiskit.validation.ModelValidationError in qiskit v0.19
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.validation.ModelValidationError
---

# ModelValidationError

<Class id="qiskit.validation.ModelValidationError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit/tree/stable/0.14/qiskit/validation/exceptions.py" signature="ModelValidationError(message, field_name=None, data=None, valid_data=None, **kwargs)" modifiers="exception">
  Raised when a sequence subscript is out of range.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.validation.ModelValidationError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

