---
title: IBMQAccountCredentialsInvalidFormat
description: API reference for qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat
---

<span id="qiskit-providers-ibmq-ibmqaccountcredentialsinvalidformat" />

# qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat

<Class id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/exceptions.py" signature="IBMQAccountCredentialsInvalidFormat(*message)" modifiers="exception">
  Errors raised when the credentials format is invalid.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.IBMQAccountCredentialsInvalidFormat.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

