---
title: IBMQBackendApiProtocolError
description: API reference for qiskit.providers.ibmq.IBMQBackendApiProtocolError
in_page_toc_min_heading_level: 1
python_api_type: exception
python_api_name: qiskit.providers.ibmq.IBMQBackendApiProtocolError
---

<span id="qiskit-providers-ibmq-ibmqbackendapiprotocolerror" />

# qiskit.providers.ibmq.IBMQBackendApiProtocolError

<Class id="qiskit.providers.ibmq.IBMQBackendApiProtocolError" isDedicatedPage={true} github="https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.12/qiskit/providers/ibmq/exceptions.py" signature="IBMQBackendApiProtocolError(*message)" modifiers="exception">
  Errors raised when an unexpected value is received from the server.

  Set the error message.

  ### with\_traceback

  <Function id="qiskit.providers.ibmq.IBMQBackendApiProtocolError.with_traceback" signature="with_traceback()">
    Exception.with\_traceback(tb) â€“ set self.\_\_traceback\_\_ to tb and return self.
  </Function>
</Class>

